2025-05-11 19:01:26 | ERROR | stderr | /opt/conda/envs/chatba/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".
2025-05-11 19:01:26 | ERROR | stderr | 
2025-05-11 19:01:26 | ERROR | stderr | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
2025-05-11 19:01:26 | ERROR | stderr |   warnings.warn(
2025-05-11 19:02:02 | ERROR | stderr | /opt/conda/envs/chatba/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".
2025-05-11 19:02:02 | ERROR | stderr | 
2025-05-11 19:02:02 | ERROR | stderr | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
2025-05-11 19:02:02 | ERROR | stderr |   warnings.warn(
2025-05-11 19:02:32 | ERROR | stderr | /opt/conda/envs/chatba/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".
2025-05-11 19:02:32 | ERROR | stderr | 
2025-05-11 19:02:32 | ERROR | stderr | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
2025-05-11 19:02:32 | ERROR | stderr |   warnings.warn(
2025-05-11 19:02:59 | ERROR | stderr | /opt/conda/envs/chatba/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".
2025-05-11 19:02:59 | ERROR | stderr | 
2025-05-11 19:02:59 | ERROR | stderr | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
2025-05-11 19:02:59 | ERROR | stderr |   warnings.warn(
2025-05-11 19:05:29 | ERROR | stderr | /opt/conda/envs/chatba/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".
2025-05-11 19:05:29 | ERROR | stderr | 
2025-05-11 19:05:29 | ERROR | stderr | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
2025-05-11 19:05:29 | ERROR | stderr |   warnings.warn(
